### ISSUE TITLE
랜딩 페이지 구현

### ISSUE THREAD

**Issue by sykang013** [likelion-reactproject-lab12/together#13]
자동으로 좌측으로 흘러감. 데이터 받아와서랜덤 뿌리기.[링크](https://github.com/orgs/likelion-reactproject-lab12/projects/3/views/1?filterQuery=%EB%9E%9C%EB%94%A9&pane=issue&itemId=22372019)
GSAP 스크롤 트리거 [링크](https://github.com/orgs/likelion-reactproject-lab12/projects/3/views/1?filterQuery=%EB%9E%9C%EB%94%A9&pane=issue&itemId=22371869)
버튼 로그인 이동 [링크](https://github.com/orgs/likelion-reactproject-lab12/projects/3/views/1?filterQuery=%EB%9E%9C%EB%94%A9&pane=issue&itemId=22275461)

## Description
- 랜딩 페이지 구현 작업
- 일단은 마크업과 스타일링을 생각
- 이미지는 더미로 가져온다 (map 사용)

## Todo
- [x] [페이지 분석](https://www.figma.com/file/M6sMGyTiiqKC9RnQKNfM6C/Untitled?node-id=0%3A1&t=RRFE6aGuYI7IKrbq-1)
- [x] 컴포넌트 계획 스케치
- [x] 브랜치 생성
- [x] react slick 라이브러리 css import 설치

## Linked Issue
- [x]  #36 
- [x]  #47 
- [x] #55 
- [x] #60 
  - [x] 스토리북 에러 : 컴포넌트 또는 스토리 레벨에서 withRouter 데코레이터가 필요한 경우만 설정해 사용
  - [x] GSAP 에러 :  사이드이펙트 처리
- [x] #77 
- [x] #65 
- [x] #62
- [x] #64 
- [ ] 🔥 challenge - 동영상 컨테이너 구현(티빙홈페이지 참고)
- [x] 전체 반응형 동작 확인

## ETC

**Comment by sykang013** [comment]
### 버튼 컴포넌트 제작
![Image](https://user-images.githubusercontent.com/113448786/224750326-f86a7302-9f1c-40be-9a26-a844cdbb7ea4.png)


- `<button>` 으로 해야할지` <a>` 로 해야할지 고민했으나, 클릭시 '로그인 페이지'로 넘어가기에 MDN 문서를 참고하여 <a>로 진행하기로 하였다.
- [MDN 문서 button태그](https://developer.mozilla.org/ko/docs/Web/HTML/Element/button)
![Image](https://user-images.githubusercontent.com/113448786/224749957-ba9670fa-2481-4728-a9ea-87bd00b1c40d.png)

- [MDN 문서 a태그](https://developer.mozilla.org/ko/docs/Web/HTML/Element/a)
![Image](https://user-images.githubusercontent.com/113448786/224750046-83df2464-91cb-44ad-a927-75d801703130.png)

-<a> target 사용시 주의 
target="_blank"를 rel="noreferrer"와 rel="noopener" 없이 사용하면 웹사이트가 [window.opener](https://developer.mozilla.org/ko/docs/Web/API/Window/opener) API 악용 공격에 취약해집니다. ([취약점 설명](https://www.jitbit.com/alexblog/256-targetblank---the-most-underestimated-vulnerability-ever/)) 다만, 최근 브라우저(Firefox 79+ 등)는 target="_blank"를 지정하면 임의로 rel="noopener" 설정과 동일한 보호 수준을 적용합니다.

**Comment by sykang013** [comment]
Layout.jsx 로인해 배경이미지/캐러셀이 꽉 차게 구현하는것이 어려움.
-> Layout.jsx 을 수정해 랜딩페이지 전용 레이아웃을 사용할 수 있지만, 이럴 경우 불필요한 렌더링을 줄인다는것이 무의미해지는것이 아닌건가(헤더, 푸터) 하는 의문이 듬. 좀 더 작업해본 후 디스커션 또는 이슈에서 올리기.
