### ISSUE TITLE
랜딩 페이지 점검

### ISSUE THREAD

**Issue by sykang013** [likelion-reactproject-lab12/together#133]
## Description
- 랜딩페이지 점검

## Todo
- [x] 웹표준 준수 체크
- [x] img 대체 텍스트 추가로 웹접근성 개선
- [x] RWD 체크 320px~1920px 
- [ ] PR후 Merge
