### ISSUE TITLE
프로필 마크업

### ISSUE THREAD

**Issue by kyungseob7** [likelion-reactproject-lab12/together#16]
프로필 클릭 시 메인페이지로 이동
버튼 클릭 시 프로필편집으로 이동
사진과 이름 변경
완료 클릭 시 프로필선택으로

## Description 
-
- 

## Todo
- [ ] 컴포넌트 단위로 마크업
- [ ] 클릭 시 이동 기능
- [ ] 사진과 이름 변경 기능 
## ETC
