### ISSUE TITLE
타입스크립트 마이그레이션

### ISSUE THREAD

**Issue by senasoon** [likelion-reactproject-lab12/together#30]
## Description 
타입스크립트 마이그레이션

## Todo
- [x] 기존 파일 .ts, .tsx로 변환
- [x] types 폴더 생성
- [x] typescript 설치 및 tsconfig 설정

## ETC
기타사항

**Comment by senasoon** [comment]
타입스크립트 설정을 현재 레포지터리의 `ts/develop` 브랜치에 설정해두었습니다!
