### ISSUE TITLE
globalstyle 추가, 스토리북7 설치 등 환경설정

### ISSUE THREAD

**Issue by sykang013** [likelion-reactproject-lab12/together#31]
## Description
- 환경설정 개선
- 공통 스타일 추가 및 수정

## Todo
- [x] GlobalStyle.jsx 내용 추가
  - #27 디스커션 참고.
- [x] 기존 stortbook6.5 삭제 및 storybook7(베타)설치
- [x] storybook7 'process is nit defined' 에러 해결 및 정상 구동 확인
  - vite.config.js 수정 ([참고링크](https://github.com/yamoo9/likelion-FEQA/issues/127))
- [x] slcik-carousel 설치
- [x] gsap 설치
- [x] PR merge 완료시 이슈 close

## ETC
기타사항

**Comment by sykang013** [comment]
PR 및 merge 완료되었으므로 이슈 닫습니다.
