### ISSUE TITLE
IconButton 스토리북으로 구현

### ISSUE THREAD

**Issue by sykang013** [likelion-reactproject-lab12/together#36]
## Description
- CDD(component driven development)를 위한 스토리북 테스트 
- 스토리북 사용히 컴포넌트를 각각 개별적으로 구동하는것이 가능하며, 문서화에 큰 도움을 받을 수 있다.
- 스토리북은 독립적이므로 세팅만 해놓고 사용하지 않아도 된다.
- 현재 7버젼은 아직 beta버젼임.

## Todo
- [x] 스토리북 세팅
- [x] 스토리북 7버젼으로 변경
- [x] #46
- [x] 문제 해결
- [x] 메인페이지 IconButton 버튼 구현 #13
- [x] proptypes를 꼭 써야한다. 
- [x] 메타데이터는 디폴트 내보내기, 스토리는 export로 받는다.(API 약속)
- [x] .defaultProps 사용
- [ ] 주석과 기록 꼼꼼하게 남기기
- [ ] PR 요청
- [ ] Develop 브랜치에 병합

## ETC
-  팀 전원이 스토리북 무경험자이며, 프로젝트 마감과 러닝커브를 고려해보았을 때 기능구현이 일단은 먼저라고 판단하여, 스토리북 사용에 대한 안건은 보류상태로 전환합니다. (23/03/12)
- CDD 등에 대한 이슈로 스토리북을 사용하는 방향으로 전환합니다. (23/03/15)

**Comment by sykang013** [comment]
### issue
스토리북에서 절대경로 먹히지 않는 문제 발생. [질문참고](https://github.com/yamoo9/likelion-FEQA/issues/129) 하였으나, 설치된 버젼이 7임에도 먹히지 않음. 상대경로로 바꿔주면 정상작동됨.

**Comment by sykang013** [comment]
### issue
Cannot destructure property 'basename' of 'React2.useContext(...)' as it is null.
![Image](https://user-images.githubusercontent.com/113448786/225357745-15552a0c-8d9f-437b-b6f8-accad353815a.png)
[질문링크](https://github.com/yamoo9/likelion-FEQA/issues/134) 참고하여 해결시도
- [x]  `npm i -D storybook-addon-react-router-v6 --legacy-peer-deps`
- [x] `npm install react-is --legacy-peer-deps`

**Comment by sykang013** [comment]
팀 내에서 스토리북 사용하지 않기로 논의되었으므로 close 합니다
