### ISSUE TITLE
푸터

### ISSUE THREAD

**Issue by pingandthepong** [likelion-reactproject-lab12/together#4]
## Todo
- [ ] Footer Mark up 추가
- [ ] Footer Assets 추가
- [ ] Footer styling 추가
- [ ] Develop 브랜치에 footer 브랜치 병합

## ETC
