### ISSUE TITLE
스타일 시스템 세팅

### ISSUE THREAD

**Issue by sykang013** [likelion-reactproject-lab12/together#5]
## Description
일관된 작업을 위한 공통 스타일 시스템 세팅

## Todo
- [x] font style 15종 정리
- [x] color 변환 함수 수정 
- [x] 작동 이상 없는지 확인
- [x] PR요청 #6 
- [x] Develop 브랜치에 병합

## ETC

**Comment by sykang013** [comment]
PR 및 Develop 브랜치 병합 완료로 이슈 close 합니다.
