### ISSUE TITLE
'오프닝 컨테이너' 애니메이션 구현

### ISSUE THREAD

**Issue by sykang013** [likelion-reactproject-lab12/together#55]
## Description
- GSAP 을 이용한 첫번째 스크롤 컨테이너 오프닝 애니메이션 구현
- 반응형이 아닌, 페이지 로드시 자동실행되는 애니메이션임.
- .fromTo(), stagger, timeline + opacity 사용
  - stagger : 단일 tween 에서 여러 대상의 시작 시점 주기
  - timeline : a의 애니메이션이 끝나고 b의 애니메이션 시작...
- .stage > div { } 
  - stage 클래스 안에 있는 div 요소 

## Todo
- [x] 애니메이션 구현 단위로 element 쪼개기  
- [x] text, button에 동일한 fromTo()애니메이션 적용
- [x] stagger로 묶어서 올리기
- [x] 백그라운드 적용

## ETC
https://greensock.com/docs/

**Comment by sykang013** [comment]
### ISSUE
- [ ] 새로고침시 GSAP 애니메이션 렌더링 되어야함
