### ISSUE TITLE
className 사용한 부분 전부 수정

### ISSUE THREAD

**Issue by sykang013** [likelion-reactproject-lab12/together#64]
## Description
- styled-components에서 class명 지양 필요
- 요소검사시 className으로 준 것이 변형되어있지 않으므로, 같은 클래스명 중복을 피하기 위해 className을 props로 사용
- [x] 스타일드 컴포넌트 자체가 모든 클래스명을 변형해주는거같은데 직접 클래스명으로 사용하는 경우에는 안되는것으로 추정(확인필요)
- 방법1
```
@media (min-width: 1920px) {
  ${(props) =>
    props.className==='sub' &&
    css`
        ${getFontStyle('~~')}
    `}
} 
```
- 방법2
  - nth-child 이용

## Todo
- [x] 전체 수정 필요 😭 
- [x] 컴포넌트
  - [x] ~Carousel~ => GSAP으로 바꿀거라 일단 넘김
  - [x] MessageAd
  - [x] MessageTitle
  - [x] PrimaryButton
- [x] 컨테이너
  - [x] ScrollSectionAd
  - [x] ScrollSectionTitle 
  - [x] ScrollSectionNow
  - [x] ScrollSectionOriginal
- [x] 페이지

**Comment by sykang013** [comment]
반영하여 이슈 닫습니다
