### ISSUE TITLE
'티빙에만있는재미' 컨테이너 구현

### ISSUE THREAD

**Issue by sykang013** [likelion-reactproject-lab12/together#65]
## Description
- GSAP 스크롤 트리거 활용
- 브라우저 크기에 따른 img 처리 방법
  - [x] `<picture>` `<source>` 사용
  - ~media query~
  - ~window.matchMedia~
  - ~GSAP에서 제공해주는 부분 있는지?~

## Todo
- [x] 구조분석 
- [x] 이미지 부족한 이슈 파악 
- [x] srcset을 이용한 모바일, 태블릿+데스크탑 사진 변경 적용
- [x] GSAP 스크롤 트리거 활용을 위한 스크롤 트리거 컨테이너 및 캐러셀 마크업+CSS디자인 
- [ ] 모바일&테블릿(세로로 긴 형태) 이미지 스크롤 트리거 적용
- [ ] 데스크탑(가로로 긴 형태) 이미지 스크롤 트리거 적용
- [ ] 이미지(4장)이 모두 넘어가면 다음 스크롤 섹션 등장
- [ ] 포커스 되지않은(중앙에 위치하지않은) 사진은 dim 처리

**Comment by sykang013** [comment]
랜딩페이지 애니메이션 관련 이슈를 따로 관리하기 위해, 해당 이슈는 닫습니다.
