### ISSUE TITLE
랜딩페이지 애니메이션(ScrollTrigger,AutoPlay) 적용

### ISSUE THREAD

**Issue by sykang013** [likelion-reactproject-lab12/together#77]
## Description
- GSAP 스크롤 트리거 활용
- 브라우저 크기에 따른 img 처리 방법
- '티빙에만 있는 재미' :  gsap.scrollTrigger() 
  - [매서드참고](https://greensock.com/docs/v3/HelperFunctions#loop)
- '내가 찾던 재미' : CSS 기본 애니메이션 무한루프([참고](https://codepen.io/studiojvla/pen/qVbQqW)) 

## Todo
- [x] '티빙에만 있는 재미' scrollTrigger 구현
- [x] '내가 찾던 재미' 무한루프 오토플레이 애니메이션
- [x] 반응형에서의 작동 확인

## ETC
