### ISSUE TITLE
실시간 인기 프로그램 캐러셀 구현

### ISSUE THREAD

**Issue by sykang013** [likelion-reactproject-lab12/together#8]
## Description
- 모바일에서부터 시작한다.
- 리액트 슬릭을 사용한다.
- flex, gap 

## Todo
- [x] 새 개인 브랜치 생성
- [x] components 폴더 생성
- [x] 작업할 carousel 파일 생성
- [x] 작업중(일단 커밋)
- [ ] 구현 확인
- [ ] 웹접근성-키보드
- [ ] 웹접근성-스크린리더
- [ ] 모바일, 태블릿, 데스크탑 환경에서의 작동 확인
- [ ] origin develop 브랜치 병합
- [ ] upstream develop 브랜치 PR 요청
- [ ] upstream develop 브랜치 병합 확인

## ETC
