### ISSUE TITLE
티빙에서 꼭 봐야하는 콘텐츠 캐러셀 구현

### ISSUE THREAD

**Issue by guahyoung** [likelion-reactproject-lab12/together#9]
## Description
메인페이지 티빙에서 꼭 봐야하는 콘텐츠 캐러셀 기능 구현 

## Todo
- [x] 개인 작업 브랜치 생성 
- [ ] 마크업 
- [ ] 스타일링
- [ ] slick으로 캐러셀 기능 구현 
- [ ] 반응형(모바일,태블릿,데스크탑) 만들기

## ETC
