### ISSUE TITLE
랜딩페이지 리팩토링 : 파이어베이스 이미지 불러오기, 웹접근성 등

### ISSUE THREAD

**Issue by sykang013** [likelion-reactproject-lab12/together#93]
## Description
- 랜딩페이지 리팩토링 

## Todo
- [x] 랜딩페이지 필요 이미지 티빙 사이트에서 가져와서 최적화
- [x] 랜딩페이지에 필요한 이미지 파이어베이스 업로드
- [x] 티빙 -> 타잉으로 수정
- [x] 이미지 파이어베이스에서 불러오기 (또는 한번만 다운로드 되면 더이상 이미지 불러오지 않도록?)
- [x] map 으로 이미지 뿌리기 
- [ ] 반복되는 코드 줄이기(코드 라인 비교 필요)
- [ ] 코드 스플리팅(컴포넌트화)
- [x] 최소한의 웹접근성 고려
  - [x] 이미지 대체 텍스트 
  - [x] 키보드 접근성
    - 랜딩페이지에서 tab키 누를 경우, '프라이머리' 버튼 두 가지만 일단 선택되고 있음.(그밖에 헤더, 푸더) 
  - [x] SEO 
    - helmet 적용

## ETC
